In [88]:
# from google.colab import drive
# drive.mount('/content/drive/')
path = "/content/drive/Shareddrives/KAIST FELab Offline Team/Task/Data/"
import pandas as pd
import numpy as np
import copy
# df1 = pd.read_csv(path + "coin_mv2.csv")
df1 = pd.read_csv('coin_mv2.csv',index_col='Date',parse_dates=True)
df1 = df1[::-1]
df1

,BTC,ETH,MANA,FIL,XTZ,XMR,ZEC,ZRX,ANT,ETC,...,MKR,THETA,IOST,ONT,REN,ELF,REP,NMR,DCR,MLN
Date,,,,,,,,,,,,,,,,,,,,,
2018-12-31,65331499158,13886837730,47699470,0,281040876,771405409,315126763,163922551,11179586,541060545,...,330600519,33321752,62090150,172311979,12829581,30076674,86035432,3100517,150490493,6067442
2019-01-01,67098634181,14665318370,49109537,0,288374540,807214007,333412878,175361171,11634823,560395114,...,336000438,35180697,66479311,176798158,13780416,31834841,90147231,3216448,158586779,6143327
2019-01-02,68849856732,16150049902,49336677,0,294826017,872187905,342252065,181968082,12238266,583194524,...,361862964,35746139,71468406,187817527,13946510,33169683,97553509,3561184,167312119,7067991
2019-01-03,66994920903,15536849936,46501936,0,292890866,831627236,326191639,177553060,11790158,546424216,...,365544044,37457246,68456310,176569460,13300985,32662215,95028923,3587885,165795529,6759721
2019-01-04,67368333500,16107068093,48064824,0,293434817,845363922,327191560,178736296,12016408,563663345,...,363017440,36365287,69504469,177931636,13484813,34194190,101704442,3533200,168857455,6960483
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-27,957746390396,480134213401,6823122904,5576472195,4434770127,3979880588,2267996914,742861173,370275249,4965622350,...,2646663745,5469887380,661013235,659499778,622702568,221228047,210238421,203839673,1076296880,156256770
2021-12-28,900076230597,452043198574,6107446057,5181339196,3903605854,3769725674,2003460754,679141042,485082368,4619506148,...,2464542662,5089114841,592506872,603619256,582975242,203189666,195932278,197588057,990994026,220930653
2021-12-29,878478755242,431593692098,5931475888,4891010924,3779147297,3872089276,1960671852,644208956,434063827,4502173069,...,2323878780,4904890890,575958644,574590273,553369250,198633333,189088387,186041178,942493582,166217480
2021-12-30,892386327929,441792512827,6008485369,5017137686,3793766780,4075865508,2053348311,675517286,443265738,4568618819,...,2367494225,4816830839,580523226,586779788,557225030,205113778,192459151,189046474,981446392,159899842
2021-12-31,875939356679,438128003491,5967477220,4927606463,3799072176,4131545841,1967453776,681732244,534927730,4504131123,...,2305746025,4714737796,566234118,575889060,528610750,203341913,199630669,185718106,953190578,159122205

In [89]:
# df2 = pd.read_csv(path + "coin_price.csv")
df2 = pd.read_csv('coin_price.csv',index_col='Date',parse_dates=True)
df2 = df2[::-1]
df2

,BTC,ETH,MANA,FIL,XTZ,XMR,ZEC,ZRX,ANT,ETC,...,MKR,THETA,IOST,ONT,REN,ELF,REP,NMR,DCR,MLN
Date,,,,,,,,,,,,,,,,,,,,,
2018-12-31,3742.70,139.86,0.05,2.82,0.46,46.23,56.54,0.30,0.38,5.05,...,453.98,0.05,0.01,0.59,0.02,0.11,7.82,2.96,16.58,7.47
2019-01-01,3843.52,140.82,0.05,3.02,0.47,48.37,59.75,0.32,0.40,5.23,...,461.39,0.05,0.01,0.61,0.02,0.11,8.20,2.99,17.46,7.56
2019-01-02,3943.41,155.05,0.05,3.34,0.49,52.25,61.25,0.33,0.42,5.44,...,496.91,0.05,0.01,0.65,0.02,0.12,8.87,2.79,18.42,8.70
2019-01-03,3836.74,149.14,0.04,3.34,0.48,49.82,58.31,0.32,0.40,5.09,...,501.96,0.05,0.01,0.61,0.02,0.12,8.64,3.02,18.24,8.32
2019-01-04,3857.72,154.58,0.05,3.46,0.48,50.63,58.41,0.32,0.41,5.25,...,498.49,0.05,0.01,0.61,0.02,0.12,9.25,3.24,18.56,8.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-27,50640.42,4037.55,3.74,39.15,5.08,220.45,169.31,0.88,9.35,37.64,...,2682.08,5.47,0.04,0.75,0.62,0.41,19.11,27.94,79.00,87.16
2021-12-28,47588.85,3800.89,3.35,36.29,4.48,208.80,149.48,0.80,12.25,35.02,...,2497.82,5.09,0.03,0.69,0.58,0.37,17.81,27.94,72.72,123.24
2021-12-29,46444.71,3628.53,3.25,34.17,4.33,214.47,146.21,0.76,10.96,34.12,...,2355.26,4.90,0.03,0.66,0.55,0.37,17.19,28.09,69.15,92.72
2021-12-30,47178.13,3713.85,3.29,34.97,4.35,225.75,153.04,0.80,11.19,34.62,...,2399.52,4.82,0.03,0.67,0.56,0.38,17.50,27.36,71.99,89.20
2021-12-31,46306.45,3682.63,3.27,34.27,4.35,228.82,146.56,0.80,13.51,34.12,...,2337.19,4.71,0.03,0.66,0.53,0.37,18.15,28.47,69.90,88.76

In [90]:
df3 = pd.read_csv('코인모음.csv',index_col='category',parse_dates=True)
df3_ind = df3.index
lst_coin = []
# df4 = df1.copy()
for i in df3_ind:
    b = df3.loc[i]
    a= b.tolist()
    c= a[0].split(',')
    lst_coin.append(c)
lst_coin

[['BTC', 'ETH', 'MANA', 'FIL', 'XTZ', 'XMR', 'ZEC', 'ZRX', 'ANT'],
 ['BTC', 'ETH', 'MANA', 'FIL', 'ETC', 'ZEC', 'BAT', 'LPT', 'ZEN', 'CVC'],
 ['BTC', 'ETH', 'XMR', 'MKR', 'ZEC'],
 ['BTC', 'ETH', 'THETA', 'IOST', 'ONT', 'REN', 'ELF'],
 ['BTC', 'ETH', 'MKR', 'BAT', 'REP'],
 ['BTC', 'ETH', 'MKR', 'ZEC', 'DCR', 'ZRX', 'ANT', 'NMR', 'MLN']]

In [91]:
price_mv = []
price_pr = []
for i in range(len(lst_coin)):
    df4 = df1.copy()
    df5 = df2.copy()
    df6 = df1.copy()
    df7 = df2.copy()
    for j in df1.columns:
        if j not in lst_coin[i]:
            df4 = df4.drop(j, axis=1)
            df6 = df6.drop(j, axis=1)
            df5 = df5.drop(j, axis=1)
            df7 = df7.drop(j, axis=1)
    df4['total_mv'] = df4.sum(axis=1)
    df5['total_pr'] = df5.sum(axis=1)
    for k in df6.columns:
        df4[k] = df4[k]/df4['total_mv']
        df5[k] = df5[k]/df5['total_pr']
    df4 = df4.drop('total_mv', axis=1)
    df5 = df5.drop('total_pr', axis=1)
    df8 = df4*df7
    df9 = df5*df7
    df10 = df8.sum(axis=1)
    df11 = df9.sum(axis=1)
    price_mv.append(df10)
    price_pr.append(df11)
for i in range(len(price_mv)):
    if i == 0:
        df_mv = price_mv[0]
    else:
        df_mv = pd.concat([df_mv,price_mv[i]], axis=1)
for j in range(len(price_pr)):
    if j == 0:
        df_pr = price_pr[0]
    else:
        df_pr = pd.concat([df_pr,price_pr[j]], axis=1)
df_mv.columns = ['price_mv_boostvc_portfolio', 'price_mv_dcg_portfolio', 'price_mv_electric_capital_portfolio', 'price_mv_huobi_capital_portfolio','price_mv_1confirmation_portfolio', 'price_mv_placeholder_ventures_portfolio']
df_pr.columns = ['price_pr_boostvc_portfolio', 'price_pr_dcg_portfolio', 'price_pr_electric_capital_portfolio', 'price_pr_huobi_capital_portfolio','price_pr_1confirmation_portfolio', 'price_pr_placeholder_ventures_portfolio']
df_pr

,price_pr_boostvc_portfolio,price_pr_dcg_portfolio,price_pr_electric_capital_portfolio,price_pr_huobi_capital_portfolio,price_pr_1confirmation_portfolio,price_pr_placeholder_ventures_portfolio
Date,,,,,,
2018-12-31,3517.550897,3545.473953,3207.434474,3612.190659,3276.224164,3220.479332
2019-01-01,3612.254581,3642.777925,3296.390244,3711.908904,3368.931773,3310.234476
2019-01-02,3695.169850,3729.252289,3361.299867,3799.303632,3436.189275,3376.290108
2019-01-03,3598.483943,3630.643299,3263.873023,3698.009365,3334.702159,3277.341994
2019-01-04,3614.074002,3647.012265,3281.585249,3714.301119,3352.626762,3295.052773
...,...,...,...,...,...,...
2021-12-27,46817.040049,46886.245918,44814.429086,47192.862918,45101.490296,44826.354828
2021-12-28,43995.839988,44069.755603,42131.349714,44344.370453,42395.277322,42109.088825
2021-12-29,42987.882901,43064.630180,41218.521321,43336.425238,41486.290946,41227.909534
2021-12-30,43636.205544,43723.799810,41836.940189,44000.732758,42118.151070,41855.912289
2021-12-31,42798.414399,42892.291508,41049.670567,43160.970041,41327.458726,41070.275303

In [92]:
price_dj = []
for i in range(len(lst_coin)):
    df13 = df2.copy()
    for j in df1.columns:
        if j not in lst_coin[i]:
            df13 = df13.drop(j,axis=1)
    df14 = df13/len(df13.columns)
    df15 = df13.sum(axis=1)
    price_dj.append(df15)
    
for i in range(len(price_dj)):
    if i == 0:
        df_dj = price_dj[0]
    else:
        df_dj = pd.concat([df_dj,price_dj[i]], axis=1)

df_dj.columns = ['price_dj_boostvc_portfolio', 'price_dj_dcg_portfolio', 'price_dj_electric_capital_portfolio', 'price_dj_huobi_capital_portfolio','price_dj_1confirmation_portfolio', 'price_dj_placeholder_ventures_portfolio']
df_dj

,price_dj_boostvc_portfolio,price_dj_dcg_portfolio,price_dj_electric_capital_portfolio,price_dj_huobi_capital_portfolio,price_dj_1confirmation_portfolio,price_dj_placeholder_ventures_portfolio
Date,,,,,,
2018-12-31,3989.34,3957.34,4439.31,3883.34,4344.49,4420.77
2019-01-01,4096.72,4061.77,4553.85,3985.14,4454.06,4534.21
2019-01-02,4216.59,4177.34,4708.87,4099.31,4604.38,4687.28
2019-01-03,4098.59,4061.62,4595.97,3986.69,4496.61,4576.45
2019-01-04,4126.06,4088.11,4619.83,4013.11,4520.18,4600.30
...,...,...,...,...,...,...
2021-12-27,55125.93,55043.70,57749.81,54685.26,57380.54,57733.69
2021-12-28,51805.19,51717.46,54245.84,51396.50,53906.59,54273.99
2021-12-29,50487.39,50396.50,52789.18,50079.75,52446.84,52776.39
2021-12-30,51325.37,51221.53,53670.29,50898.44,53310.19,53645.08
2021-12-31,50420.66,50309.23,52701.65,49995.38,52345.63,52674.27

In [93]:
df_mv.to_csv('price_mv.csv')
df_pr.to_csv('price_pr.csv')
df_dj.to_csv('price_dj.csv')